name: Mama Feet
favicon: null
layout_spectrum: 0.8420978432986885
typography_spectrum: 0.07316014147363603
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff029d'
    - '#a8ff00'
    - '#ffffff'
    - '#cf76b4'
    - '#fabaf7'
  brandStrength: 0.1875
  lightness: 0.3125
  saturation: 0.32470070477575064
  rhythmicContrast: 0.25
purpose: []
