name: Realidade Musical
favicon: null
layout_spectrum: 0.45438
typography_spectrum: 0.64213
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#f60000'
    - '#7a0c0c'
    - '#cc8884'
    - '#eaadad'
  brandStrength: 0.1875
  lightness: 0.3125
  saturation: 0.32470070477575064
  rhythmicContrast: 0.25
purpose: []
